In [64]:
import numpy as np

In [65]:
b = np.array([1,2,3])
b
print(b)

[1 2 3]


In [66]:
c = np.array([[1,4,9],[16,25,36]])
print(c)

[[ 1  4  9]
 [16 25 36]]


In [67]:
#get dimension of array
c.ndim

2

In [68]:
#get shape
c.shape

(2, 3)

In [69]:
#get type 
c.dtype

dtype('int32')

In [70]:
p = np.array([[1,3,5],[7,9,11],[13,15,17]],dtype='int8')
print(p)
p.dtype

[[ 1  3  5]
 [ 7  9 11]
 [13 15 17]]


dtype('int8')

In [71]:
#get size (factor)
b.itemsize

4

In [72]:
p.itemsize

1

In [73]:
#get size of the array
c.size

6

In [74]:
#get no. of bytes (size*factor),also the total bytes used
c.nbytes

24

In [75]:
print(c)

[[ 1  4  9]
 [16 25 36]]


In [76]:
#getting a specific element out of an array
c[0][1]

4

In [77]:
#get a specific row,column
c[1,:]

array([16, 25, 36])

In [78]:
c[:,2]

array([ 9, 36])

In [79]:
#iterating through array's
print(p)

[[ 1  3  5]
 [ 7  9 11]
 [13 15 17]]


In [80]:
p[1,0:3]

array([ 7,  9, 11], dtype=int8)

In [81]:
#replace existing element
p[2,2]=19
print(p)

[[ 1  3  5]
 [ 7  9 11]
 [13 15 19]]


In [82]:
#3-d array
q=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(q)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [83]:
#accessing an element
q[1,0,1]

6

In [84]:
q[:,0,:]

array([[1, 2],
       [5, 6]])

#initialising arrays in different ways
1.
np.zeros((2,2))

In [85]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [86]:
np.full((1,2,3),45)

array([[[45, 45, 45],
        [45, 45, 45]]])

In [87]:
np.full_like(p.shape,4)

array([4, 4])

In [88]:
np.full(p.shape,3)

array([[3, 3, 3],
       [3, 3, 3],
       [3, 3, 3]])

In [89]:
#2.
np.random.rand(2,3)

array([[0.24041656, 0.41503923, 0.85357425],
       [0.35930935, 0.73492087, 0.17951335]])

In [90]:
np.random.randint(10,size=(2,2))

array([[2, 1],
       [9, 6]])

In [91]:
#3.
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [92]:
#4.Repeat an array
print(np.repeat(np.array([[1,2,3]]),3,axis=0))

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [93]:
a1=np.ones((5,5))
print(a1)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [94]:
a2=np.zeros((3,3))
print(a2)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [95]:
a2[1,1]=9
print(a2)

[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]


In [96]:
a1[1:4,1:4]=a2
print(a1)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [97]:
a=np.array([1,2,3,4])
b=a
b[2]=7
print(a)

[1 2 7 4]


In [98]:
c=a.copy()
c[2]=45
print(a)

[1 2 7 4]


In [99]:
b1=np.array([1,2,3,4])
b2=np.array([1,4,9,16])
b1+b2

array([ 2,  6, 12, 20])

In [100]:
b1*b2

array([ 1,  8, 27, 64])

In [101]:
b2/b1

array([1., 2., 3., 4.])

## Linear Algebra

In [102]:
#Matrix Multiplication
a=np.identity(2)
b=np.full((2,3),5)

In [103]:
np.matmul(a,b)

array([[5., 5., 5.],
       [5., 5., 5.]])

In [104]:
#Determinant of a matrix
np.linalg.det(a)

1.0

#We can find multiplication,determinant,trace,eigen values,inverse etc using various inbuilt functions of the numpy library

## Statistics

In [105]:
statarr=np.array([[81,64,49],[121,144,169]])
statarr

array([[ 81,  64,  49],
       [121, 144, 169]])

In [106]:
#Find minimum of the array
np.min(statarr)

49

In [107]:
#Find maximum of the array
np.max(statarr)

169

In [108]:
np.min(statarr,axis=0)

array([81, 64, 49])

In [109]:
np.max(statarr,axis=1)

array([ 81, 169])

In [110]:
#Find sum of the array
np.sum(statarr)

628

In [111]:
np.sum(statarr,axis=0)

array([202, 208, 218])

## Reorganizing Arrays

In [112]:
#Reorganizing works so long as product of dimensions of the original and the changed matrix is the same
before=np.array([[1,3,5,7],[7,5,3,1],[1,2,4,8]])
print(before)
after=before.reshape((6,2))
print(after)

[[1 3 5 7]
 [7 5 3 1]
 [1 2 4 8]]
[[1 3]
 [5 7]
 [7 5]
 [3 1]
 [1 2]
 [4 8]]


In [113]:
#vertically stacking matrices
v1=np.zeros((2,2))
v2=np.ones((2,2))
np.vstack([v1,v2,v1])

array([[0., 0.],
       [0., 0.],
       [1., 1.],
       [1., 1.],
       [0., 0.],
       [0., 0.]])

In [114]:
#horizontally stack matrices
v1=np.zeros((2,3))
v2=np.ones((2,2))
np.hstack([v1,v2,v1])

array([[0., 0., 0., 1., 1., 0., 0., 0.],
       [0., 0., 0., 1., 1., 0., 0., 0.]])

## Miscellaneous

In [115]:
#load data from a file (without pandas)
filedata=np.genfromtxt('sample.txt',dtype=int,delimiter=',')
filedata

array([[      1,       2,       4,       8,      16,      32,      64,
            128],
       [  65536,  121072,  262144,  524288, 1048576, 2097152, 4194304,
        8388608],
       [    256,     512,    1024,    2048,    4096,    8192,   16384,
          32768]])

In [116]:
filedata=filedata.astype('int32')
filedata

array([[      1,       2,       4,       8,      16,      32,      64,
            128],
       [  65536,  121072,  262144,  524288, 1048576, 2097152, 4194304,
        8388608],
       [    256,     512,    1024,    2048,    4096,    8192,   16384,
          32768]])

## Boolean Masking and Advanced Indexing

In [117]:
#Returns a boolean array of elements satisfying the condition or not
filedata>256

array([[False, False, False, False, False, False, False, False],
       [ True,  True,  True,  True,  True,  True,  True,  True],
       [False,  True,  True,  True,  True,  True,  True,  True]])

In [118]:
#Returns elements satisfying the condition or not
filedata[filedata > 65536]

array([ 121072,  262144,  524288, 1048576, 2097152, 4194304, 8388608])

In [119]:
#indexing with a list
ab=np.array([1,2,3,4,5,6,7,8,9])
ab[[1,4,7]]

array([2, 5, 8])

In [121]:
np.any(filedata>524288,axis=0)

array([False, False, False, False,  True,  True,  True,  True])

In [122]:
np.all(filedata>524288,axis=0)

array([False, False, False, False, False, False, False, False])

In [125]:
((filedata>256) & (filedata%65536==0))

array([[False, False, False, False, False, False, False, False],
       [ True, False,  True,  True,  True,  True,  True,  True],
       [False, False, False, False, False, False, False, False]])

In [126]:
~((filedata>256) & (filedata%65536==0))

array([[ True,  True,  True,  True,  True,  True,  True,  True],
       [False,  True, False, False, False, False, False, False],
       [ True,  True,  True,  True,  True,  True,  True,  True]])